# Generated by Django 2.0.4 on 2018-05-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseExplorer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KooferData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0.0)),
                ('num_ratings', models.IntegerField(default=0)),
                ('gpa', models.FloatField(default=0.0)),
            ],
        ),
    ]
